import { useEffect, useState } from 'react';
import { Bell, X, PackageX, AlertTriangle } from 'lucide-react';
import { Link } from 'react-router-dom';
import { api } from '../lib/api.js';

export default function NotificationCenter(){
 const [rows,setRows]=useState([]),[open,setOpen]=useState(false),[error,setError]=useState(''),[offline,setOffline]=useState(false);
 useEffect(()=>{let live=true;const load=()=>api.get('/api/notifications').then(r=>{if(live){setRows(r.data||[]);setOffline(Boolean(r.offline));}}).catch(e=>{if(live)setError(e.message);});load();const t=setInterval(load,60000);window.addEventListener('online',load);return()=>{live=false;clearInterval(t);window.removeEventListener('online',load);};},[]);
 async function mark(row){try{await api.post(`/api/notifications/${row.id}/read`,{});setRows(current=>current.map(r=>r.id===row.id?{...r,read:true}:r));}catch(e){setError(e.message);}}
 const count=rows.filter(r=>!r.read).length;
 return <><button aria-label={`Stock notifications${count?`, ${count} unread`:''}`} onClick={()=>setOpen(true)} className="relative rounded-xl border border-slate-200 p-2.5 text-slate-600"><Bell size={19}/>{count>0&&<span className="absolute -right-1 -top-1 rounded-full bg-red-600 px-1.5 text-[10px] font-bold text-white">{count>99?'99+':count}</span>}</button>{open&&<div className="fixed inset-0 z-50 bg-slate-950/40" onClick={()=>setOpen(false)}><section role="dialog" aria-modal="true" aria-label="Stock notifications" className="absolute inset-y-0 right-0 flex w-full max-w-md flex-col bg-white shadow-xl" onClick={e=>e.stopPropagation()}><header className="flex items-center justify-between border-b p-5"><div><h2 className="text-lg font-bold">Stock notifications</h2><p className="text-xs text-slate-500">{offline?'Saved alerts · connect for updates':'Parts that need your attention'}</p></div><button aria-label="Close notifications" onClick={()=>setOpen(false)}><X/></button></header><div className="flex-1 overflow-auto p-4">{error&&<p className="mb-3 text-sm text-red-700" role="alert">{error}</p>}{rows.length?rows.map(r=><article key={r.id} className={`mb-3 rounded-xl border p-4 ${r.read?'border-slate-200':'border-amber-200 bg-amber-50'}`}><div className="flex gap-3">{r.kind==='out'?<PackageX className="shrink-0 text-red-600" size={20}/>:<AlertTriangle className="shrink-0 text-amber-600" size={20}/>}<div><h3 className="text-sm font-semibold">{r.title}</h3><p className="mt-1 text-sm text-slate-600">{r.message}</p><p className="mt-2 text-xs text-slate-500">{new Date(r.created_at).toLocaleString()}</p><div className="mt-3 flex gap-4 text-xs font-semibold"><Link to="/reorder" onClick={()=>setOpen(false)}>Review restocking</Link>{!r.read&&<button disabled={offline} onClick={()=>mark(r)}>Mark as read</button>}</div></div></div></article>):<p className="py-12 text-center text-sm text-slate-500">No stock alerts yet.</p>}</div></section></div>}</>;
}
