import { useEffect, useMemo, useState } from 'react';
import { BrainCircuit, Play, Search, TriangleAlert, Database, TrendingUp } from 'lucide-react';
import { CartesianGrid, Line, LineChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';
import { api } from '../lib/api.js';
import PageHeader from '../components/PageHeader.jsx';
import Loading from '../components/Loading.jsx';
import StatusBadge from '../components/StatusBadge.jsx';
import Toast from '../components/Toast.jsx';
import { useAuth } from '../context/AuthContext.jsx';

export default function ForecastPage(){
 const {profile}=useAuth(); const canTrain=['owner','admin'].includes(profile?.role);
 const [runs,setRuns]=useState([]),[quality,setQuality]=useState(null),[forecastProducts,setForecastProducts]=useState([]),[query,setQuery]=useState(''),[selected,setSelected]=useState(''),[forecast,setForecast]=useState([]),[loading,setLoading]=useState(true),[training,setTraining]=useState(false),[includeProxy,setIncludeProxy]=useState(false),[horizon,setHorizon]=useState(30),[toast,setToast]=useState(null);
 const load=async()=>{setLoading(true);try{const [r,q,fp]=await Promise.all([api.get('/api/forecast/runs'),api.get('/api/data-quality'),api.get('/api/forecast/products')]);setRuns(r.data||[]);setQuality(q);setForecastProducts(fp.data||[]);if(!selected&&fp.data?.length)setSelected(fp.data[0].product_id);}catch(e){setToast({type:'error',message:e.message});}finally{setLoading(false);}};
 useEffect(()=>{load();},[]);
 useEffect(()=>{if(!selected){setForecast([]);return;}api.get(`/api/forecast/product/${selected}`).then(r=>setForecast(r.data||[])).catch(e=>setToast({type:'error',message:e.message}));},[selected,runs]);
 const filtered=useMemo(()=>forecastProducts.filter(p=>(`${p.part_number||''} ${p.description}`).toLowerCase().includes(query.toLowerCase())).slice(0,30),[forecastProducts,query]);
 const selectedProduct=forecastProducts.find(p=>p.product_id===selected);
 async function train(){setTraining(true);try{const r=await api.post('/api/forecast/train',{horizonDays:Number(horizon),includeProxy});setToast({message:`XGBoost completed: ${r.forecastCount} future forecast rows created.`});setSelected('');await load();}catch(e){setToast({type:'error',message:e.message});}finally{setTraining(false);}}
 if(loading)return <Loading label="Loading forecasting module..."/>;
 const latest=runs[0];
 return <><PageHeader title="Demand Forecast" subtitle="XGBoost Regression for intermittent spare-parts demand using actual sales and imported training observations." actions={canTrain?<button className="btn-primary" disabled={training} onClick={train}><Play size={16}/>{training?'Training XGBoost...':'Train & Forecast'}</button>:null}/>
  <div className="grid gap-3 sm:grid-cols-3"><div className="panel p-4"><div className="flex items-center gap-2 text-xs font-semibold text-slate-500"><Database size={15}/>Imported training rows</div><p className="mt-2 text-2xl font-bold">{Number(quality?.importedTrainingRows||0).toLocaleString()}</p></div><div className="panel p-4"><div className="flex items-center gap-2 text-xs font-semibold text-slate-500"><TrendingUp size={15}/>Forecasted products</div><p className="mt-2 text-2xl font-bold">{forecastProducts.length.toLocaleString()}</p></div><div className="panel p-4"><div className="flex items-center gap-2 text-xs font-semibold text-slate-500"><BrainCircuit size={15}/>Actual sale rows</div><p className="mt-2 text-2xl font-bold">{Number(quality?.actualDemandRows||0).toLocaleString()}</p></div></div>
  <div className="mt-5 grid gap-5 xl:grid-cols-[.85fr_1.15fr]">
   <div className="space-y-5">
    <section className="panel p-5"><div className="flex items-start gap-3"><BrainCircuit className="mt-0.5 text-red-600"/><div><h2 className="font-bold text-slate-900">Training controls</h2><p className="mt-1 text-sm leading-6 text-slate-500">Imported XGBoost training data is included automatically. Actual PartCast sales are also included. The legacy 1-unit proxy stays optional.</p></div></div>{canTrain&&<div className="mt-5 grid gap-4"><label><span className="label">Forecast horizon</span><select className="input" value={horizon} onChange={e=>setHorizon(e.target.value)}><option value="14">14 days</option><option value="30">30 days</option><option value="60">60 days</option><option value="90">90 days</option></select></label><label className="flex items-start gap-3 rounded-xl border border-amber-200 bg-amber-50 p-4"><input type="checkbox" className="mt-1" checked={includeProxy} onChange={e=>setIncludeProxy(e.target.checked)}/><div><p className="text-sm font-semibold text-amber-900">Also include legacy transaction proxy</p><p className="mt-1 text-xs leading-5 text-amber-800">Optional only. Your training-ready spreadsheet is already imported separately and does not require this setting.</p></div></label></div>}</section>
    <section className="panel overflow-hidden"><div className="panel-header"><h2 className="font-bold">Data quality</h2></div><div className="grid grid-cols-2 gap-px bg-slate-100"><div className="bg-white p-4"><p className="text-xs text-slate-500">Imported training</p><p className="mt-1 text-2xl font-bold">{quality?.importedTrainingRows||0}</p></div><div className="bg-white p-4"><p className="text-xs text-slate-500">Legacy proxy</p><p className="mt-1 text-2xl font-bold">{quality?.proxyDemandRows||0}</p></div><div className="bg-white p-4"><p className="text-xs text-slate-500">Legacy sales rows</p><p className="mt-1 text-2xl font-bold">{quality?.legacySalesRows||0}</p></div><div className="bg-white p-4"><p className="text-xs text-slate-500">Unmatched legacy sales</p><p className="mt-1 text-2xl font-bold">{quality?.unmatchedLegacySales||0}</p></div></div></section>
    <section className="panel overflow-hidden"><div className="panel-header"><h2 className="font-bold">Recent model runs</h2></div><div className="divide-y divide-slate-100">{runs.length?runs.slice(0,8).map(r=><div className="px-5 py-3" key={r.id}><div className="flex items-center justify-between gap-3"><p className="text-sm font-semibold">{r.model_version||'XGBoost training run'}</p><StatusBadge status={r.status}/></div><p className="mt-1 text-xs text-slate-500">{new Date(r.started_at).toLocaleString()} · {r.training_rows} observations · {r.product_count} source products</p>{r.metrics&&<p className="mt-1 text-xs text-slate-600">MAE {r.metrics.mae ?? '—'} · RMSE {r.metrics.rmse ?? '—'} · R² {r.metrics.r2 ?? '—'} · WAPE {r.metrics.wape_percent ?? '—'}%</p>}</div>):<p className="p-5 text-sm text-slate-500">No model has been trained yet. Import the training-ready spreadsheet first.</p>}</div></section>
   </div>
   <section className="panel overflow-hidden"><div className="panel-header"><div><h2 className="font-bold">Product forecast</h2><p className="text-sm text-slate-500">Only products actually forecast by the latest completed model are shown here.</p></div></div><div className="border-b border-slate-100 p-4 sm:p-5"><div className="relative"><Search size={17} className="absolute left-3 top-3 text-slate-400"/><input className="input pl-10" placeholder="Search forecasted part number or description" value={query} onChange={e=>setQuery(e.target.value)}/></div>{query&&<div className="mt-2 max-h-52 overflow-y-auto rounded-lg border border-slate-200">{filtered.map(p=><button key={p.product_id} className="block w-full border-b border-slate-100 px-3 py-2 text-left text-sm last:border-0 hover:bg-slate-50" onClick={()=>{setSelected(p.product_id);setQuery('');}}><span className="font-semibold">{p.part_number||'N/A'}</span> · {p.description}<span className="float-right text-xs text-slate-500">{Number(p.predicted_total||0).toFixed(2)}</span></button>)}</div>}{selectedProduct&&<div className="mt-3 flex flex-wrap items-center gap-x-4 gap-y-1 text-xs text-slate-600"><span className="font-semibold text-slate-900">{selectedProduct.part_number||'N/A'} · {selectedProduct.description}</span><span>Horizon total: {Number(selectedProduct.predicted_total||0).toFixed(2)} units</span></div>}</div>{selected&&forecast.length?<div className="h-[420px] p-4"><ResponsiveContainer width="100%" height="100%"><LineChart data={forecast}><CartesianGrid strokeDasharray="3 3" vertical={false}/><XAxis dataKey="forecast_date" tick={{fontSize:11}} tickFormatter={v=>v.slice(5)}/><YAxis tick={{fontSize:11}}/><Tooltip formatter={v=>[Number(v).toFixed(3),'Predicted demand']}/><Line type="monotone" dataKey="predicted_quantity" stroke="#dc2626" strokeWidth={2.5} dot={false}/></LineChart></ResponsiveContainer></div>:<div className="flex min-h-[420px] flex-col items-center justify-center p-8 text-center"><TriangleAlert className="text-slate-300" size={34}/><p className="mt-3 text-sm font-semibold text-slate-700">{quality?.importedTrainingRows?'Run Train & Forecast to generate visible predictions.':'Import your XGBoost training-ready spreadsheet first.'}</p><p className="mt-1 max-w-md text-xs leading-5 text-slate-500">The improved model requires at least 5 observed demand days and about 35 days of history for each forecasted product.</p></div>}</section>
  </div><Toast toast={toast} onClose={()=>setToast(null)}/></>;
}
