import { useEffect, useMemo, useState } from 'react';
import { BrainCircuit, Play, Search, TriangleAlert } from 'lucide-react';
import { CartesianGrid, Line, LineChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';
import { api } from '../lib/api.js';
import PageHeader from '../components/PageHeader.jsx';
import Loading from '../components/Loading.jsx';
import StatusBadge from '../components/StatusBadge.jsx';
import Toast from '../components/Toast.jsx';
import { useAuth } from '../context/AuthContext.jsx';

export default function ForecastPage(){
 const {profile}=useAuth(); const canTrain=['owner','admin'].includes(profile?.role);
 const [runs,setRuns]=useState([]),[quality,setQuality]=useState(null),[products,setProducts]=useState([]),[query,setQuery]=useState(''),[selected,setSelected]=useState(''),[forecast,setForecast]=useState([]),[loading,setLoading]=useState(true),[training,setTraining]=useState(false),[includeProxy,setIncludeProxy]=useState(false),[horizon,setHorizon]=useState(30),[toast,setToast]=useState(null);
 const load=async()=>{setLoading(true);try{const [r,q,p]=await Promise.all([api.get('/api/forecast/runs'),api.get('/api/data-quality'),api.get('/api/products?page=1&pageSize=100&q=&status=all')]);setRuns(r.data||[]);setQuality(q);setProducts(p.data||[]);}catch(e){setToast({type:'error',message:e.message});}finally{setLoading(false);}};
 useEffect(()=>{load();},[]);
 useEffect(()=>{if(!selected){setForecast([]);return;}api.get(`/api/forecast/product/${selected}`).then(r=>setForecast(r.data||[])).catch(e=>setToast({type:'error',message:e.message}));},[selected]);
 const filtered=useMemo(()=>products.filter(p=>(`${p.part_number||''} ${p.description}`).toLowerCase().includes(query.toLowerCase())).slice(0,20),[products,query]);
 async function train(){setTraining(true);try{const r=await api.post('/api/forecast/train',{horizonDays:Number(horizon),includeProxy});setToast({message:`Forecast completed with ${r.forecastCount} forecast rows.`});await load();}catch(e){setToast({type:'error',message:e.message});}finally{setTraining(false);}}
 if(loading)return <Loading label="Loading forecasting module..."/>;
 const latest=runs[0];
 return <><PageHeader title="Demand Forecast" subtitle="XGBoost Regression forecasts future spare-parts demand from dated quantity observations." actions={canTrain?<button className="btn-primary" disabled={training} onClick={train}><Play size={16}/>{training?'Training XGBoost...':'Train & forecast'}</button>:null}/>
  <div className="grid gap-5 xl:grid-cols-[.85fr_1.15fr]">
   <div className="space-y-5">
    <section className="panel p-5"><div className="flex items-start gap-3"><BrainCircuit className="mt-0.5 text-red-600"/><div><h2 className="font-bold text-slate-900">Training controls</h2><p className="mt-1 text-sm leading-6 text-slate-500">Actual quantity sales are the preferred training source. Legacy invoice rows can be used as a transaction-count proxy only when explicitly enabled.</p></div></div>{canTrain&&<div className="mt-5 grid gap-4"><label><span className="label">Forecast horizon</span><select className="input" value={horizon} onChange={e=>setHorizon(e.target.value)}><option value="14">14 days</option><option value="30">30 days</option><option value="60">60 days</option><option value="90">90 days</option></select></label><label className="flex items-start gap-3 rounded-xl border border-amber-200 bg-amber-50 p-4"><input type="checkbox" className="mt-1" checked={includeProxy} onChange={e=>setIncludeProxy(e.target.checked)}/><div><p className="text-sm font-semibold text-amber-900">Include legacy transaction proxy</p><p className="mt-1 text-xs leading-5 text-amber-800">Use only for demonstration when the old sales workbook has no reliable quantity-per-line values. Results must not be presented as exact unit-demand history.</p></div></label></div>}</section>
    <section className="panel overflow-hidden"><div className="panel-header"><h2 className="font-bold">Data quality</h2></div><div className="grid grid-cols-2 gap-px bg-slate-100"><div className="bg-white p-4"><p className="text-xs text-slate-500">Actual demand rows</p><p className="mt-1 text-2xl font-bold">{quality?.actualDemandRows||0}</p></div><div className="bg-white p-4"><p className="text-xs text-slate-500">Proxy rows</p><p className="mt-1 text-2xl font-bold">{quality?.proxyDemandRows||0}</p></div><div className="bg-white p-4"><p className="text-xs text-slate-500">Legacy sales rows</p><p className="mt-1 text-2xl font-bold">{quality?.legacySalesRows||0}</p></div><div className="bg-white p-4"><p className="text-xs text-slate-500">Unmatched legacy sales</p><p className="mt-1 text-2xl font-bold">{quality?.unmatchedLegacySales||0}</p></div></div></section>
    <section className="panel overflow-hidden"><div className="panel-header"><h2 className="font-bold">Recent model runs</h2></div><div className="divide-y divide-slate-100">{runs.length?runs.slice(0,8).map(r=><div className="px-5 py-3" key={r.id}><div className="flex items-center justify-between gap-3"><p className="text-sm font-semibold">{r.model_version||'XGBoost training run'}</p><StatusBadge status={r.status}/></div><p className="mt-1 text-xs text-slate-500">{new Date(r.started_at).toLocaleString()} · {r.training_rows} rows · {r.product_count} products</p>{r.metrics&&<p className="mt-1 text-xs text-slate-600">MAE {r.metrics.mae ?? '—'} · RMSE {r.metrics.rmse ?? '—'} · R² {r.metrics.r2 ?? '—'}</p>}</div>):<p className="p-5 text-sm text-slate-500">No model has been trained yet.</p>}</div></section>
   </div>
   <section className="panel overflow-hidden"><div className="panel-header"><div><h2 className="font-bold">Product forecast</h2><p className="text-sm text-slate-500">Select a product to inspect future predicted quantity.</p></div></div><div className="border-b border-slate-100 p-4 sm:p-5"><div className="relative"><Search size={17} className="absolute left-3 top-3 text-slate-400"/><input className="input pl-10" placeholder="Find a product" value={query} onChange={e=>setQuery(e.target.value)}/></div>{query&&<div className="mt-2 max-h-52 overflow-y-auto rounded-lg border border-slate-200">{filtered.map(p=><button key={p.id} className="block w-full border-b border-slate-100 px-3 py-2 text-left text-sm last:border-0 hover:bg-slate-50" onClick={()=>{setSelected(p.id);setQuery(`${p.part_number||'N/A'} · ${p.description}`);}}><span className="font-semibold">{p.part_number||'N/A'}</span> · {p.description}</button>)}</div>}</div>{selected&&forecast.length?<div className="h-[420px] p-4"><ResponsiveContainer width="100%" height="100%"><LineChart data={forecast}><CartesianGrid strokeDasharray="3 3" vertical={false}/><XAxis dataKey="forecast_date" tick={{fontSize:11}} tickFormatter={v=>v.slice(5)}/><YAxis tick={{fontSize:11}}/><Tooltip/><Line type="monotone" dataKey="predicted_quantity" stroke="#dc2626" strokeWidth={2.5} dot={false}/></LineChart></ResponsiveContainer></div>:<div className="flex min-h-[420px] flex-col items-center justify-center p-8 text-center"><TriangleAlert className="text-slate-300" size={34}/><p className="mt-3 text-sm font-semibold text-slate-700">{selected?'No forecast is available for this product.':'Choose a product to view its forecast.'}</p><p className="mt-1 max-w-md text-xs leading-5 text-slate-500">A product needs sufficient dated demand observations to be included in model training.</p></div>}</section>
  </div><Toast toast={toast} onClose={()=>setToast(null)}/></>;
}
