import { useEffect, useState } from 'react';
import { FileSpreadsheet, UploadCloud, TriangleAlert } from 'lucide-react';
import { api } from '../lib/api.js';
import PageHeader from '../components/PageHeader.jsx';
import StatusBadge from '../components/StatusBadge.jsx';
import Toast from '../components/Toast.jsx';

export default function ImportPage(){
 const [inventory,setInventory]=useState(null),[sales,setSales]=useState(null),[useProxy,setUseProxy]=useState(false),[busy,setBusy]=useState(''),[history,setHistory]=useState([]),[toast,setToast]=useState(null);
 const load=()=>api.get('/api/imports').then(r=>setHistory(Array.isArray(r?.data)?r.data:[])).catch(e=>setToast({type:'error',message:e.message}));
 useEffect(()=>{ load(); },[]);
 async function send(kind,file){if(!file)return;setBusy(kind);try{const fd=new FormData();fd.append('file',file);if(kind==='legacy-sales')fd.append('useProxy',String(useProxy));const r=await api.post(`/api/imports/${kind}`,fd);setToast({message:`Imported ${r.rowsImported} rows. ${r.rowsSkipped} skipped.`});load();}catch(e){setToast({type:'error',message:e.message});}finally{setBusy('');}}
 return <><PageHeader title="Import Data" subtitle="Securely migrate NPG Autoparts Excel workbooks after deployment. Raw source files do not need to be stored in the public code repository."/>
  <div className="grid gap-5 lg:grid-cols-2">
   <section className="panel p-5"><div className="flex items-center gap-3"><div className="rounded-xl bg-emerald-50 p-3 text-emerald-700"><FileSpreadsheet size={21}/></div><div><h2 className="font-bold">Inventory-npg workbook</h2><p className="text-sm text-slate-500">Imports the Inventory snapshot, suppliers, product-supplier relationships, and historical purchases.</p></div></div><label className="mt-5 block rounded-xl border-2 border-dashed border-slate-200 p-6 text-center hover:border-slate-300"><UploadCloud className="mx-auto text-slate-400"/><p className="mt-2 text-sm font-semibold">{inventory?.name||'Choose Inventory-npg .xlsx'}</p><input type="file" accept=".xlsx" className="sr-only" onChange={e=>setInventory(e.target.files?.[0]||null)}/></label><button className="btn-primary mt-4 w-full" disabled={!inventory||busy==='inventory'} onClick={()=>send('inventory',inventory)}>{busy==='inventory'?'Importing...':'Import inventory workbook'}</button></section>
   <section className="panel p-5"><div className="flex items-center gap-3"><div className="rounded-xl bg-blue-50 p-3 text-blue-700"><FileSpreadsheet size={21}/></div><div><h2 className="font-bold">Customer reference transactions</h2><p className="text-sm text-slate-500">Imports historical invoice references for reporting and attempts to match part numbers in item text.</p></div></div><label className="mt-5 block rounded-xl border-2 border-dashed border-slate-200 p-6 text-center hover:border-slate-300"><UploadCloud className="mx-auto text-slate-400"/><p className="mt-2 text-sm font-semibold">{sales?.name||'Choose CUST-REF-TRANS .xlsx'}</p><input type="file" accept=".xlsx" className="sr-only" onChange={e=>setSales(e.target.files?.[0]||null)}/></label><label className="mt-4 flex items-start gap-3 rounded-xl border border-amber-200 bg-amber-50 p-4"><input className="mt-1" type="checkbox" checked={useProxy} onChange={e=>setUseProxy(e.target.checked)}/><div><p className="text-sm font-semibold text-amber-900">Create 1-unit legacy demand proxy</p><p className="mt-1 text-xs leading-5 text-amber-800">The provided legacy sales format contains amount and item text but does not reliably provide quantity per item. Enable this only to create a transaction-count proxy for model demonstration.</p></div></label><button className="btn-primary mt-4 w-full" disabled={!sales||busy==='legacy-sales'} onClick={()=>send('legacy-sales',sales)}>{busy==='legacy-sales'?'Importing...':'Import sales workbook'}</button></section>
  </div>
  <div className="mt-5 flex gap-3 rounded-xl border border-slate-200 bg-white p-4"><TriangleAlert className="mt-0.5 shrink-0 text-amber-600" size={19}/><p className="text-sm leading-6 text-slate-600">Import on a fresh database first. The main inventory worksheet is treated as the current-stock snapshot; the supplier worksheets are stored as purchase history so they do not double-count current quantity.</p></div>
  <section className="panel mt-5 overflow-hidden"><div className="panel-header"><h2 className="font-bold">Import history</h2></div><div className="overflow-x-auto"><table className="min-w-full text-sm"><thead className="bg-slate-50 text-left text-xs uppercase text-slate-500"><tr><th className="px-5 py-3">File</th><th className="px-4 py-3">Type</th><th className="px-4 py-3">Status</th><th className="px-4 py-3 text-right">Read</th><th className="px-4 py-3 text-right">Imported</th><th className="px-5 py-3">Date</th></tr></thead><tbody className="divide-y divide-slate-100">{history.map(h=><tr key={h.id}><td className="px-5 py-3 font-medium">{h.file_name}</td><td className="px-4 py-3 text-slate-600">{String(h.import_type||'unknown').replaceAll('_',' ')}</td><td className="px-4 py-3"><StatusBadge status={h.status}/></td><td className="px-4 py-3 text-right">{h.rows_read}</td><td className="px-4 py-3 text-right">{h.rows_imported}</td><td className="px-5 py-3 text-slate-500">{h.created_at?new Date(h.created_at).toLocaleString():'—'}</td></tr>)}</tbody></table></div></section>
  <Toast toast={toast} onClose={()=>setToast(null)}/></>;
}
