import { useEffect, useMemo, useState } from 'react';
import { FileSpreadsheet, UploadCloud, TriangleAlert, CheckCircle2 } from 'lucide-react';
import { api } from '../lib/api.js';
import PageHeader from '../components/PageHeader.jsx';
import StatusBadge from '../components/StatusBadge.jsx';
import Toast from '../components/Toast.jsx';

const typeLabel={auto:'Auto detect from columns',inventory:'Inventory / purchase history','legacy-sales':'Historical sales / customer references','demand-training':'XGBoost demand training data'};

export default function ImportPage(){
 const [files,setFiles]=useState([]),[kind,setKind]=useState('auto'),[useProxy,setUseProxy]=useState(false),[busy,setBusy]=useState(false),[history,setHistory]=useState([]),[toast,setToast]=useState(null),[results,setResults]=useState([]);
 const load=()=>api.get('/api/imports').then(r=>setHistory(Array.isArray(r?.data)?r.data:[])).catch(e=>setToast({type:'error',message:e.message}));
 useEffect(()=>{load();},[]);
 const names=useMemo(()=>files.map(f=>f.name).join(', '),[files]);
 async function send(){if(!files.length||busy)return;setBusy(true);setResults([]);const done=[];try{for(const file of files){const fd=new FormData();fd.append('file',file);fd.append('kind',kind);fd.append('useProxy',String(useProxy));try{const r=await api.post('/api/imports/spreadsheet',fd);done.push({file:file.name,ok:true,...r});}catch(e){done.push({file:file.name,ok:false,error:e.message});}}setResults(done);const ok=done.filter(x=>x.ok).length;setToast({type:ok===done.length?'success':'error',message:`${ok} of ${done.length} spreadsheet(s) imported successfully.`});load();}finally{setBusy(false);}}
 return <><PageHeader title="Import Data" subtitle="Upload Excel or CSV files with any file name. PartCast can identify supported datasets from their column structure."/>
  <section className="panel p-5">
   <div className="grid gap-5 lg:grid-cols-[1fr_.8fr]">
    <div><div className="flex items-center gap-3"><div className="rounded-xl bg-emerald-50 p-3 text-emerald-700"><FileSpreadsheet size={22}/></div><div><h2 className="font-bold">Smart spreadsheet import</h2><p className="text-sm text-slate-500">Supported formats: .xlsx, .xlsm, and .csv. The base file name is not validated.</p></div></div>
     <label className="mt-5 block cursor-pointer rounded-xl border-2 border-dashed border-slate-200 p-7 text-center hover:border-red-300 hover:bg-red-50/30"><UploadCloud className="mx-auto text-slate-400" size={28}/><p className="mt-2 text-sm font-semibold text-slate-800">{files.length?`${files.length} spreadsheet(s) selected`:'Choose one or more spreadsheets'}</p><p className="mt-1 truncate text-xs text-slate-500">{names||'Inventory, historical sales, or XGBoost training data'}</p><input type="file" multiple accept=".xlsx,.xlsm,.csv,application/vnd.openxmlformats-officedocument.spreadsheetml.sheet,text/csv" className="sr-only" onChange={e=>setFiles([...e.target.files])}/></label>
    </div>
    <div className="space-y-4"><label><span className="label">Import type</span><select className="input" value={kind} onChange={e=>setKind(e.target.value)}>{Object.entries(typeLabel).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label><div className="rounded-xl border border-slate-200 bg-slate-50 p-4 text-xs leading-5 text-slate-600"><p className="font-semibold text-slate-800">Auto detect recognizes:</p><p className="mt-1">Inventory: Part Number/Description + Quantity</p><p>Sales: Ref/Invoice + Date + Customer + Items</p><p>Training: Date + Part Number + Demand Quantity</p></div>{(kind==='legacy-sales'||kind==='auto')&&<label className="flex items-start gap-3 rounded-xl border border-amber-200 bg-amber-50 p-4"><input className="mt-1" type="checkbox" checked={useProxy} onChange={e=>setUseProxy(e.target.checked)}/><div><p className="text-sm font-semibold text-amber-900">Allow 1-unit legacy proxy for detected sales files</p><p className="mt-1 text-xs leading-5 text-amber-800">Leave off when you are importing the separate training-ready workbook.</p></div></label>}<button className="btn-primary w-full" disabled={!files.length||busy} onClick={send}>{busy?'Importing spreadsheets...':'Import selected spreadsheets'}</button></div>
   </div>
  </section>
  {results.length>0&&<section className="panel mt-5 overflow-hidden"><div className="panel-header"><h2 className="font-bold">Latest import results</h2></div><div className="divide-y divide-slate-100">{results.map((r,i)=><div key={`${r.file}-${i}`} className="flex items-start gap-3 px-5 py-4">{r.ok?<CheckCircle2 className="mt-0.5 shrink-0 text-emerald-600" size={19}/>:<TriangleAlert className="mt-0.5 shrink-0 text-red-600" size={19}/>}<div className="min-w-0"><p className="break-all text-sm font-semibold text-slate-900">{r.file}</p>{r.ok?<p className="mt-1 text-xs leading-5 text-slate-600">Detected {String(r.detectedType||'spreadsheet').replaceAll('-',' ')}{r.selectedSheet?` · training sheet: ${r.selectedSheet}`:''}{r.snapshotSheet?` · stock sheet: ${r.snapshotSheet}`:''} · {r.rowsImported} rows imported · {r.rowsSkipped} skipped.</p>:<p className="mt-1 text-xs text-red-700">{r.error}</p>}</div></div>)}</div></section>}
  <div className="mt-5 flex gap-3 rounded-xl border border-blue-200 bg-blue-50 p-4"><TriangleAlert className="mt-0.5 shrink-0 text-blue-700" size={19}/><p className="text-sm leading-6 text-blue-900"><span className="font-semibold">For your supplied datasets:</span> import the cleaned inventory spreadsheet first, then the cleaned customer/sales spreadsheet, then the PartCast XGBoost training-ready spreadsheet. The demand-training importer automatically chooses the strongest usable Date + Part Number + Demand Quantity table and matches it to existing inventory part numbers.</p></div>
  <section className="panel mt-5 overflow-hidden"><div className="panel-header"><h2 className="font-bold">Import history</h2></div><div className="overflow-x-auto"><table className="min-w-full text-sm"><thead className="bg-slate-50 text-left text-xs uppercase text-slate-500"><tr><th className="px-5 py-3">File</th><th className="px-4 py-3">Type</th><th className="px-4 py-3">Status</th><th className="px-4 py-3 text-right">Read</th><th className="px-4 py-3 text-right">Imported</th><th className="px-5 py-3">Date</th></tr></thead><tbody className="divide-y divide-slate-100">{history.map(h=><tr key={h.id}><td className="px-5 py-3 font-medium">{h.file_name}</td><td className="px-4 py-3 text-slate-600">{String(h.import_type||'unknown').replaceAll('_',' ')}</td><td className="px-4 py-3"><StatusBadge status={h.status}/></td><td className="px-4 py-3 text-right">{h.rows_read}</td><td className="px-4 py-3 text-right">{h.rows_imported}</td><td className="px-5 py-3 text-slate-500">{h.created_at?new Date(h.created_at).toLocaleString():'—'}</td></tr>)}</tbody></table></div></section>
  <Toast toast={toast} onClose={()=>setToast(null)}/></>;
}
