import { useEffect, useMemo, useState, useRef } from 'react';
import { ArrowDownToLine, ArrowUpFromLine, Pencil, Plus, Search, ShoppingCart } from 'lucide-react';
import { api } from '../lib/api.js';
import Modal from '../components/Modal.jsx';
import Loading from '../components/Loading.jsx';
import EmptyState from '../components/EmptyState.jsx';
import Pagination from '../components/Pagination.jsx';
import PageHeader from '../components/PageHeader.jsx';
import StatusBadge from '../components/StatusBadge.jsx';
import { useSearchParams } from 'react-router-dom';
import { useAuth } from '../context/AuthContext.jsx';
import Toast from '../components/Toast.jsx';

const blankProduct={part_number:'',sub_number:'',description:'',brand:'',unit:'pc',location:'',current_stock:0,minimum_stock:1,safety_stock:1,unit_cost:0,selling_price:0};
const blankMove={product_id:'',tx_type:'stock_in',quantity:1,unit_cost:'',unit_price:'',reference_no:'',supplier_id:'',customer_name:'',total_amount:'',notes:''};

export default function InventoryPage(){
 const [params]=useSearchParams();
 const action=params.get('action');
 const [offline,setOffline]=useState(!navigator.onLine);
 const [rows,setRows]=useState([]),[count,setCount]=useState(0),[page,setPage]=useState(1),[q,setQ]=useState(''),[status,setStatus]=useState('all'),[loading,setLoading]=useState(true);
 const [productModal,setProductModal]=useState(false),[editingId,setEditingId]=useState(null),[moveModal,setMoveModal]=useState(false),[product,setProduct]=useState(blankProduct),[move,setMove]=useState(blankMove),[suppliers,setSuppliers]=useState([]),[saving,setSaving]=useState(false),[toast,setToast]=useState(null);
 const requestNumber=useRef(0);
 const pageSize=25;
 const load=async()=>{const request=++requestNumber.current;setLoading(true);try{const r=await api.get(`/api/products?page=${page}&pageSize=${pageSize}&q=${encodeURIComponent(q)}&status=${status}`);if(request===requestNumber.current){setRows(r.data);setCount(r.count||0);}}catch(e){if(request===requestNumber.current)setToast({type:'error',message:e.message});}finally{if(request===requestNumber.current)setLoading(false);}};
 useEffect(()=>{const changed=()=>{setOffline(!navigator.onLine);load();};const reachable=e=>setOffline(!navigator.onLine||!e.detail);window.addEventListener('partcast:connection',reachable);window.addEventListener('online',changed);window.addEventListener('offline',changed);window.addEventListener('partcast:queue',changed);return()=>{window.removeEventListener('partcast:connection',reachable);window.removeEventListener('online',changed);window.removeEventListener('offline',changed);window.removeEventListener('partcast:queue',changed);};},[page,q,status]);
 useEffect(()=>{const t=setTimeout(load,250);return()=>clearTimeout(t);},[page,q,status]);
 useEffect(()=>{api.get('/api/suppliers').then(r=>setSuppliers(r.data||[])).catch(()=>{});},[]);
 const selected=useMemo(()=>rows.find(r=>r.id===move.product_id),[rows,move.product_id]);
 function openAdd(){setEditingId(null);setProduct(blankProduct);setProductModal(true);}
 function openEdit(row){setEditingId(row.id);setProduct({part_number:row.part_number||'',sub_number:row.sub_number||'',description:row.description||'',brand:row.brand||'',unit:row.unit||'',location:row.location||'',current_stock:Number(row.current_stock||0),minimum_stock:Number(row.minimum_stock||0),safety_stock:Number(row.safety_stock||0),unit_cost:Number(row.unit_cost||0),selling_price:Number(row.selling_price||0)});setProductModal(true);}
 function openMove(row,type){setMove({...blankMove,product_id:row.id,tx_type:type,unit_cost:row.unit_cost||'',unit_price:row.selling_price||''});setMoveModal(true);}
 async function saveProduct(){
  setSaving(true);
  try{
   if(editingId){
    const {current_stock,...patch}=product;
    await api.patch(`/api/products/${editingId}`,patch);
    setToast({message:'Product details and stock thresholds updated.'});
   }else{
    await api.post('/api/products',product);
    setToast({message:'Product added to inventory.'});
   }
   setProduct(blankProduct);setEditingId(null);setProductModal(false);load();
  }catch(e){setToast({type:'error',message:e.message});}finally{setSaving(false);}
 }
 async function saveMovement(){setSaving(true);try{const payload={...move,supplier_id:move.supplier_id||null,unit_cost:move.unit_cost===''?null:Number(move.unit_cost),unit_price:move.unit_price===''?null:Number(move.unit_price),total_amount:move.total_amount===''?null:Number(move.total_amount)};const result=await api.post('/api/inventory/movement',payload);setMoveModal(false);setToast({message:result.queued?'Saved on this device. It will sync automatically when connected.':`${move.tx_type.replace('_',' ')} recorded successfully.`});load();}catch(e){setToast({type:'error',message:e.message});}finally{setSaving(false);}}
 return <>
  <PageHeader title="Inventory" subtitle="Find a part, then choose what you need to do. Stock is updated after each confirmed transaction." actions={<button className="btn-primary" disabled={offline} onClick={openAdd}><Plus size={17}/>Add product</button>}/>
  <div className="mb-4 rounded-xl border border-slate-200 bg-white p-4 text-sm leading-6 text-slate-600"><strong className="text-slate-900">{action==='sale'?'Record a sale':action==='stock_in'?'Receive a delivery':'How to use Inventory'}</strong><p>1. Search for the part. &nbsp; 2. Choose <strong>{action==='sale'?'Sell':action==='stock_in'?'Receive stock':'Receive stock, Remove stock, or Sell'}</strong>. &nbsp; 3. Enter the quantity and confirm.</p></div>
  <section className="panel overflow-hidden">
   <div className="panel-header"><div className="relative w-full sm:max-w-md"><Search className="absolute left-3 top-2.5 text-slate-400" size={18}/><input className="input pl-10" aria-label="Search inventory" placeholder="Search part number, name, or brand" value={q} onChange={e=>{setQ(e.target.value);setPage(1);}}/></div><select aria-label="Filter by stock level" className="input w-full sm:w-44" value={status} onChange={e=>{setStatus(e.target.value);setPage(1);}}><option value="all">All stock</option><option value="low">Low stock</option><option value="out">Out of stock</option></select></div>
   {loading?<Loading/>:rows.length===0?<EmptyState title="No matching inventory"/>:<div className="hidden overflow-x-auto sm:block"><table className="min-w-full text-left text-sm"><thead className="bg-slate-50 text-xs uppercase tracking-wide text-slate-500"><tr><th className="px-5 py-3">Part</th><th className="px-4 py-3">Brand</th><th className="px-4 py-3 text-right">On hand</th><th className="px-4 py-3 text-right">Minimum</th><th className="px-4 py-3">Location</th><th className="px-4 py-3">Status</th><th className="px-5 py-3 text-right">Actions</th></tr></thead><tbody className="divide-y divide-slate-100">{rows.map(r=><tr key={r.id} className="hover:bg-slate-50/70"><td className="px-5 py-3"><p className="font-semibold text-slate-900">{r.part_number||'No part number'}</p><p className="mt-0.5 max-w-md truncate text-xs text-slate-500">{r.description}</p>{r.pending>0&&<p className="text-xs text-amber-700">{r.pending} unsent change(s)</p>}</td><td className="px-4 py-3 text-slate-600">{r.brand||'—'}</td><td className="px-4 py-3 text-right font-semibold">{Number(r.current_stock).toFixed(0)}</td><td className="px-4 py-3 text-right text-slate-600">{Number(r.minimum_stock).toFixed(0)}</td><td className="px-4 py-3 text-slate-600">{r.location||'—'}</td><td className="px-4 py-3"><StatusBadge status={r.stock_status}/></td><td className="px-5 py-3"><div className="flex justify-end gap-1"><button disabled={offline} title="Edit product and thresholds" className="inline-flex min-h-11 items-center gap-1 rounded-lg p-2 text-xs font-semibold text-slate-600 hover:bg-slate-100" onClick={()=>openEdit(r)}><Pencil size={17}/><span>Edit</span></button><button title="Receive stock" aria-label={`Receive stock for ${r.description}`} className="inline-flex min-h-11 items-center gap-1 rounded-lg p-2 text-xs font-semibold text-emerald-700 hover:bg-emerald-50" onClick={()=>openMove(r,'stock_in')}><ArrowDownToLine size={17}/><span>Receive</span></button><button title="Remove stock" aria-label={`Remove stock for ${r.description}`} className="inline-flex min-h-11 items-center gap-1 rounded-lg p-2 text-xs font-semibold text-amber-700 hover:bg-amber-50" onClick={()=>openMove(r,'stock_out')}><ArrowUpFromLine size={17}/><span>Remove</span></button><button title="Record sale" aria-label={`Sell ${r.description}`} className="inline-flex min-h-11 items-center gap-1 rounded-lg p-2 text-xs font-semibold text-red-700 hover:bg-red-50" onClick={()=>openMove(r,'sale')}><ShoppingCart size={17}/><span>Sell</span></button></div></td></tr>)}</tbody></table></div>}
   {!loading&&<div className="divide-y sm:hidden">{rows.map(r=><article key={r.id} className="p-4"><div className="flex items-start justify-between gap-3"><div><p className="text-sm font-bold">{r.description}</p><p className="mt-1 text-xs text-slate-500">{r.part_number||'No part number'} · {r.brand||'No brand'} · {r.location||'No location'}</p></div><StatusBadge status={r.stock_status}/></div><div className="mt-3 flex items-center justify-between"><p className="text-sm"><strong className="text-xl">{Number(r.current_stock)}</strong> {r.unit||'units'} available {r.pending>0&&<span className="block text-xs text-amber-700">Includes {r.pending} unsent change(s)</span>}</p><p className="text-xs text-slate-500">Minimum: {r.minimum_stock}</p></div><div className="mt-4 grid grid-cols-3 gap-2"><button className="btn-secondary px-2" onClick={()=>openMove(r,'stock_in')}>Receive</button><button className="btn-secondary px-2" onClick={()=>openMove(r,'stock_out')}>Remove</button><button className="btn-primary px-2" onClick={()=>openMove(r,'sale')}>Sell</button></div><button className="mt-3 text-xs font-semibold text-slate-500" disabled={offline} onClick={()=>openEdit(r)}>Edit part details</button></article>)}</div>}
   <Pagination page={page} pageSize={pageSize} count={count} onPage={setPage}/>
  </section>
  <Modal open={productModal} onClose={()=>setProductModal(false)} title={editingId?'Edit inventory product':'Add inventory product'} description={editingId?'Update product details, reorder threshold, safety stock, cost, and price. Use stock movements to change on-hand quantity.':'Create a product and optionally set its starting quantity.'} size="lg" footer={<><button className="btn-secondary" onClick={()=>setProductModal(false)}>Cancel</button><button className="btn-primary" disabled={saving} onClick={saveProduct}>{saving?'Saving...':editingId?'Save changes':'Save product'}</button></>}><div className="grid gap-4 sm:grid-cols-2"><label><span className="label">Part number</span><input className="input" value={product.part_number} onChange={e=>setProduct({...product,part_number:e.target.value})}/></label><label><span className="label">Sub number</span><input className="input" value={product.sub_number} onChange={e=>setProduct({...product,sub_number:e.target.value})}/></label><label className="sm:col-span-2"><span className="label">Description *</span><input className="input" required value={product.description} onChange={e=>setProduct({...product,description:e.target.value})}/></label><label><span className="label">Brand</span><input className="input" value={product.brand} onChange={e=>setProduct({...product,brand:e.target.value})}/></label><label><span className="label">Unit</span><input className="input" placeholder="pc, set, box" value={product.unit} onChange={e=>setProduct({...product,unit:e.target.value})}/></label><label><span className="label">Location</span><input className="input" value={product.location} onChange={e=>setProduct({...product,location:e.target.value})}/></label>{!editingId&&<label><span className="label">Starting quantity</span><input type="number" min="0" step="0.01" className="input" value={product.current_stock} onChange={e=>setProduct({...product,current_stock:e.target.value})}/></label>}{[['Minimum stock','minimum_stock'],['Safety stock','safety_stock'],['Unit cost','unit_cost'],['Selling price','selling_price']].map(([l,k])=><label key={k}><span className="label">{l}</span><input type="number" min="0" step="0.01" className="input" value={product[k]} onChange={e=>setProduct({...product,[k]:e.target.value})}/></label>)}</div></Modal>
  <Modal open={moveModal} onClose={()=>setMoveModal(false)} title={move.tx_type==='sale'?'Record sale':move.tx_type==='stock_in'?'Receive stock':'Remove stock'} description={selected?`${selected.part_number||'N/A'} · ${selected.description}`:''} size="md" footer={<><button className="btn-secondary" onClick={()=>setMoveModal(false)}>Cancel</button><button className="btn-primary" disabled={saving} onClick={saveMovement}>{saving?'Saving...':'Confirm stock change'}</button></>}><div className="space-y-4">{selected&&<div className="rounded-xl bg-slate-50 p-4 text-sm"><p>Available now: <strong>{selected.current_stock} {selected.unit||'units'}</strong></p><p className="mt-1">After this change: <strong>{Number(selected.current_stock)+(move.tx_type==='stock_in'?1:-1)*Number(move.quantity||0)} {selected.unit||'units'}</strong></p>{offline&&<p className="mt-2 text-xs text-amber-800">This change will be saved on this device until you reconnect.</p>}</div>}<label><span className="label">Quantity *</span><input className="input" type="number" min="0.01" step="0.01" value={move.quantity} onChange={e=>setMove({...move,quantity:e.target.value})}/></label>{move.tx_type==='stock_in'&&<><label><span className="label">Supplier</span><select className="input" value={move.supplier_id} onChange={e=>setMove({...move,supplier_id:e.target.value})}><option value="">Select supplier</option>{suppliers.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label><label><span className="label">Unit cost</span><input className="input" type="number" min="0" step="0.01" value={move.unit_cost} onChange={e=>setMove({...move,unit_cost:e.target.value})}/></label></>}{move.tx_type==='sale'&&<><label><span className="label">Customer name (optional)</span><input className="input" value={move.customer_name} onChange={e=>setMove({...move,customer_name:e.target.value})}/></label><div className="grid grid-cols-2 gap-3"><label><span className="label">Unit price</span><input className="input" type="number" min="0" step="0.01" value={move.unit_price} onChange={e=>setMove({...move,unit_price:e.target.value})}/></label><label><span className="label">Total amount</span><input className="input" type="number" min="0" step="0.01" value={move.total_amount} onChange={e=>setMove({...move,total_amount:e.target.value})}/></label></div></>}<label><span className="label">Reference number</span><input className="input" value={move.reference_no} onChange={e=>setMove({...move,reference_no:e.target.value})}/></label><label><span className="label">Notes</span><textarea className="input min-h-24" value={move.notes} onChange={e=>setMove({...move,notes:e.target.value})}/></label></div></Modal>
  <Toast toast={toast} onClose={()=>setToast(null)}/>
 </>;
}
