import { useEffect, useMemo, useState } from 'react';
import { ArrowDownToLine, ArrowUpFromLine, Pencil, Plus, Search, ShoppingCart } from 'lucide-react';
import { api } from '../lib/api.js';
import Modal from '../components/Modal.jsx';
import Loading from '../components/Loading.jsx';
import EmptyState from '../components/EmptyState.jsx';
import Pagination from '../components/Pagination.jsx';
import PageHeader from '../components/PageHeader.jsx';
import StatusBadge from '../components/StatusBadge.jsx';
import Toast from '../components/Toast.jsx';

const blankProduct={part_number:'',sub_number:'',description:'',brand:'',unit:'pc',location:'',current_stock:0,minimum_stock:1,safety_stock:1,unit_cost:0,selling_price:0};
const blankMove={product_id:'',tx_type:'stock_in',quantity:1,unit_cost:'',unit_price:'',reference_no:'',supplier_id:'',customer_name:'',total_amount:'',notes:''};

export default function InventoryPage(){
 const [rows,setRows]=useState([]),[count,setCount]=useState(0),[page,setPage]=useState(1),[q,setQ]=useState(''),[status,setStatus]=useState('all'),[loading,setLoading]=useState(true);
 const [productModal,setProductModal]=useState(false),[editingId,setEditingId]=useState(null),[moveModal,setMoveModal]=useState(false),[product,setProduct]=useState(blankProduct),[move,setMove]=useState(blankMove),[suppliers,setSuppliers]=useState([]),[saving,setSaving]=useState(false),[toast,setToast]=useState(null);
 const pageSize=25;
 const load=async()=>{setLoading(true);try{const r=await api.get(`/api/products?page=${page}&pageSize=${pageSize}&q=${encodeURIComponent(q)}&status=${status}`);setRows(r.data);setCount(r.count||0);}catch(e){setToast({type:'error',message:e.message});}finally{setLoading(false);}};
 useEffect(()=>{const t=setTimeout(load,250);return()=>clearTimeout(t);},[page,q,status]);
 useEffect(()=>{api.get('/api/suppliers').then(r=>setSuppliers(r.data||[])).catch(()=>{});},[]);
 const selected=useMemo(()=>rows.find(r=>r.id===move.product_id),[rows,move.product_id]);
 function openAdd(){setEditingId(null);setProduct(blankProduct);setProductModal(true);}
 function openEdit(row){setEditingId(row.id);setProduct({part_number:row.part_number||'',sub_number:row.sub_number||'',description:row.description||'',brand:row.brand||'',unit:row.unit||'',location:row.location||'',current_stock:Number(row.current_stock||0),minimum_stock:Number(row.minimum_stock||0),safety_stock:Number(row.safety_stock||0),unit_cost:Number(row.unit_cost||0),selling_price:Number(row.selling_price||0)});setProductModal(true);}
 function openMove(row,type){setMove({...blankMove,product_id:row.id,tx_type:type,unit_cost:row.unit_cost||'',unit_price:row.selling_price||''});setMoveModal(true);}
 async function saveProduct(){
  setSaving(true);
  try{
   if(editingId){
    const {current_stock,...patch}=product;
    await api.patch(`/api/products/${editingId}`,patch);
    setToast({message:'Product details and stock thresholds updated.'});
   }else{
    await api.post('/api/products',product);
    setToast({message:'Product added to inventory.'});
   }
   setProduct(blankProduct);setEditingId(null);setProductModal(false);load();
  }catch(e){setToast({type:'error',message:e.message});}finally{setSaving(false);}
 }
 async function saveMovement(){setSaving(true);try{const payload={...move,supplier_id:move.supplier_id||null,unit_cost:move.unit_cost===''?null:Number(move.unit_cost),unit_price:move.unit_price===''?null:Number(move.unit_price),total_amount:move.total_amount===''?null:Number(move.total_amount)};await api.post('/api/inventory/movement',payload);setMoveModal(false);setToast({message:`${move.tx_type.replace('_',' ')} recorded successfully.`});load();}catch(e){setToast({type:'error',message:e.message});}finally{setSaving(false);}}
 return <>
  <PageHeader title="Inventory" subtitle="Search parts, maintain stock thresholds, and record stock movement without leaving the page." actions={<button className="btn-primary" onClick={openAdd}><Plus size={17}/>Add product</button>}/>
  <section className="panel overflow-hidden">
   <div className="panel-header"><div className="relative w-full sm:max-w-md"><Search className="absolute left-3 top-2.5 text-slate-400" size={18}/><input className="input pl-10" placeholder="Search part number, description, or brand" value={q} onChange={e=>{setQ(e.target.value);setPage(1);}}/></div><select className="input w-full sm:w-44" value={status} onChange={e=>{setStatus(e.target.value);setPage(1);}}><option value="all">All stock</option><option value="low">Low stock</option><option value="out">Out of stock</option></select></div>
   {loading?<Loading/>:rows.length===0?<EmptyState title="No matching inventory"/>:<div className="overflow-x-auto"><table className="min-w-full text-left text-sm"><thead className="bg-slate-50 text-xs uppercase tracking-wide text-slate-500"><tr><th className="px-5 py-3">Part</th><th className="px-4 py-3">Brand</th><th className="px-4 py-3 text-right">On hand</th><th className="px-4 py-3 text-right">Minimum</th><th className="px-4 py-3">Location</th><th className="px-4 py-3">Status</th><th className="px-5 py-3 text-right">Actions</th></tr></thead><tbody className="divide-y divide-slate-100">{rows.map(r=><tr key={r.id} className="hover:bg-slate-50/70"><td className="px-5 py-3"><p className="font-semibold text-slate-900">{r.part_number||'No part number'}</p><p className="mt-0.5 max-w-md truncate text-xs text-slate-500">{r.description}</p></td><td className="px-4 py-3 text-slate-600">{r.brand||'—'}</td><td className="px-4 py-3 text-right font-semibold">{Number(r.current_stock).toFixed(0)}</td><td className="px-4 py-3 text-right text-slate-600">{Number(r.minimum_stock).toFixed(0)}</td><td className="px-4 py-3 text-slate-600">{r.location||'—'}</td><td className="px-4 py-3"><StatusBadge status={r.stock_status}/></td><td className="px-5 py-3"><div className="flex justify-end gap-1"><button title="Edit product and thresholds" className="rounded-lg p-2 text-slate-600 hover:bg-slate-100" onClick={()=>openEdit(r)}><Pencil size={17}/></button><button title="Stock in" className="rounded-lg p-2 text-emerald-700 hover:bg-emerald-50" onClick={()=>openMove(r,'stock_in')}><ArrowDownToLine size={17}/></button><button title="Stock out" className="rounded-lg p-2 text-amber-700 hover:bg-amber-50" onClick={()=>openMove(r,'stock_out')}><ArrowUpFromLine size={17}/></button><button title="Record sale" className="rounded-lg p-2 text-red-700 hover:bg-red-50" onClick={()=>openMove(r,'sale')}><ShoppingCart size={17}/></button></div></td></tr>)}</tbody></table></div>}
   <Pagination page={page} pageSize={pageSize} count={count} onPage={setPage}/>
  </section>
  <Modal open={productModal} onClose={()=>setProductModal(false)} title={editingId?'Edit inventory product':'Add inventory product'} description={editingId?'Update product details, reorder threshold, safety stock, cost, and price. Use stock movements to change on-hand quantity.':'Create a product and optionally set its starting quantity.'} size="lg" footer={<><button className="btn-secondary" onClick={()=>setProductModal(false)}>Cancel</button><button className="btn-primary" disabled={saving} onClick={saveProduct}>{saving?'Saving...':editingId?'Save changes':'Save product'}</button></>}><div className="grid gap-4 sm:grid-cols-2"><label><span className="label">Part number</span><input className="input" value={product.part_number} onChange={e=>setProduct({...product,part_number:e.target.value})}/></label><label><span className="label">Sub number</span><input className="input" value={product.sub_number} onChange={e=>setProduct({...product,sub_number:e.target.value})}/></label><label className="sm:col-span-2"><span className="label">Description *</span><input className="input" required value={product.description} onChange={e=>setProduct({...product,description:e.target.value})}/></label><label><span className="label">Brand</span><input className="input" value={product.brand} onChange={e=>setProduct({...product,brand:e.target.value})}/></label><label><span className="label">Unit</span><input className="input" placeholder="pc, set, box" value={product.unit} onChange={e=>setProduct({...product,unit:e.target.value})}/></label><label><span className="label">Location</span><input className="input" value={product.location} onChange={e=>setProduct({...product,location:e.target.value})}/></label>{!editingId&&<label><span className="label">Starting quantity</span><input type="number" min="0" step="0.01" className="input" value={product.current_stock} onChange={e=>setProduct({...product,current_stock:e.target.value})}/></label>}{[['Minimum stock','minimum_stock'],['Safety stock','safety_stock'],['Unit cost','unit_cost'],['Selling price','selling_price']].map(([l,k])=><label key={k}><span className="label">{l}</span><input type="number" min="0" step="0.01" className="input" value={product[k]} onChange={e=>setProduct({...product,[k]:e.target.value})}/></label>)}</div></Modal>
  <Modal open={moveModal} onClose={()=>setMoveModal(false)} title={move.tx_type==='sale'?'Record sale':move.tx_type==='stock_in'?'Record stock in':'Record stock out'} description={selected?`${selected.part_number||'N/A'} · ${selected.description}`:''} size="md" footer={<><button className="btn-secondary" onClick={()=>setMoveModal(false)}>Cancel</button><button className="btn-primary" disabled={saving} onClick={saveMovement}>{saving?'Saving...':'Record transaction'}</button></>}><div className="space-y-4"><label><span className="label">Quantity *</span><input className="input" type="number" min="0.01" step="0.01" value={move.quantity} onChange={e=>setMove({...move,quantity:e.target.value})}/></label>{move.tx_type==='stock_in'&&<><label><span className="label">Supplier</span><select className="input" value={move.supplier_id} onChange={e=>setMove({...move,supplier_id:e.target.value})}><option value="">Select supplier</option>{suppliers.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label><label><span className="label">Unit cost</span><input className="input" type="number" min="0" step="0.01" value={move.unit_cost} onChange={e=>setMove({...move,unit_cost:e.target.value})}/></label></>}{move.tx_type==='sale'&&<><label><span className="label">Customer name</span><input className="input" value={move.customer_name} onChange={e=>setMove({...move,customer_name:e.target.value})}/></label><div className="grid grid-cols-2 gap-3"><label><span className="label">Unit price</span><input className="input" type="number" min="0" step="0.01" value={move.unit_price} onChange={e=>setMove({...move,unit_price:e.target.value})}/></label><label><span className="label">Total amount</span><input className="input" type="number" min="0" step="0.01" value={move.total_amount} onChange={e=>setMove({...move,total_amount:e.target.value})}/></label></div></>}<label><span className="label">Reference number</span><input className="input" value={move.reference_no} onChange={e=>setMove({...move,reference_no:e.target.value})}/></label><label><span className="label">Notes</span><textarea className="input min-h-24" value={move.notes} onChange={e=>setMove({...move,notes:e.target.value})}/></label></div></Modal>
  <Toast toast={toast} onClose={()=>setToast(null)}/>
 </>;
}
