import {useEffect,useState} from 'react';
import {ShieldCheck,Save,RefreshCw} from 'lucide-react';
import {t,useLocale} from '../context/LocaleContext.jsx';
import {api} from '../lib/api.js';
import PageHeader from '../components/PageHeader.jsx';
import Loading from '../components/Loading.jsx';
const fields={gmail:[['client_id','Google client ID',500],['client_secret','Google client secret',1000],['refresh_token','Google refresh token',4096],['sender_email','Gmail sender address',254]],gemini:[['api_key','Gemini API key',500],['model','Gemini model',100]]};
export default function ITSettingsPage(){
 useLocale();
 const [rows,setRows]=useState([]),[draft,setDraft]=useState({}),[engine,setEngine]=useState(null),[loading,setLoading]=useState(true),[busy,setBusy]=useState(''),[error,setError]=useState(''),[message,setMessage]=useState('');
 async function load(){setLoading(true);setError('');try{const r=await api.get('/api/admin/integrations');setRows(r.data);setEngine(r.forecasting);setDraft(Object.fromEntries(r.data.map(v=>[v.provider,{enabled:v.enabled,sender_email:v.sender_email||'',model:v.model||'gemini-2.5-flash'}])));}catch(e){setError(e.message);}finally{setLoading(false);}}
 useEffect(()=>{load();},[]);
 async function save(e,provider){e.preventDefault();if(busy)return;setBusy(provider);setError('');setMessage('');try{const patch=Object.fromEntries(Object.entries(draft[provider]).filter(([k,v])=>k==='enabled'||String(v).trim()!==''));const r=await api.patch(`/api/admin/integrations/${provider}`,patch);setRows(old=>old.map(v=>v.provider===provider?r.data:v));setDraft(old=>({...old,[provider]:{enabled:r.data.enabled,sender_email:r.data.sender_email||'',model:r.data.model||'gemini-2.5-flash'}}));setMessage('Connection settings saved. Secret fields are hidden after saving.');}catch(e){setError(e.message);}finally{setBusy('');}}
 async function test(provider){if(busy)return;setBusy(provider);setError('');setMessage('');try{const r=await api.post(`/api/admin/integrations/${provider}/test`,{});setMessage(r.message);}catch(e){setError(e.message);}finally{setBusy('');}}
 return <><PageHeader title={t('IT settings')} subtitle={t('Super Admin only. Manage Google connections and check the forecasting engine.')} />
 {error&&<div role="alert" className="mb-5 rounded-xl bg-red-50 p-4 text-red-800">{t(error)}{!rows.length&&<button className="btn-secondary mt-3" onClick={load}>{t('Try again')}</button>}</div>}
 {message&&<p role="status" className="mb-5 rounded-xl bg-emerald-50 p-4 text-emerald-800">{t(message)}</p>}
 {loading?<Loading/>:<><div className="mb-5 flex items-start gap-3 rounded-xl border border-slate-200 bg-white p-4 text-sm leading-6"><ShieldCheck className="shrink-0 text-emerald-600"/><p>{t('Connection secrets are encrypted on the server and never displayed again. Leave a saved secret blank to keep it. Enter credentials only here or in server environment settings.')}</p></div>
 <div className="grid items-start gap-5 xl:grid-cols-2">{rows.map(row=><form key={row.provider} className="panel space-y-4 p-5 sm:p-6" onSubmit={e=>save(e,row.provider)}><div><h2 className="text-lg font-bold">{row.provider==='gmail'?t('Gmail login codes'):t('Gemini chatbot')}</h2><p className="mt-2 text-sm leading-6 text-slate-600">{row.provider==='gmail'?t('Send the required sign-in code through your Google account. Configure Gmail before enabling this release for staff.'):t('Answer questions after local help and saved store data have been checked.')}</p><p className={`mt-2 text-sm font-semibold ${row.ready?'text-emerald-700':'text-amber-800'}`}>{row.ready?t('Connection configured'):t('Setup needed')}</p></div>
 <fieldset disabled={Boolean(busy)} className="space-y-4">{row.provider==='gemini' && <label className="flex min-h-12 items-center gap-3"><input className="h-5 w-5" type="checkbox" checked={draft[row.provider]?.enabled??true} onChange={e=>setDraft(v=>({...v,[row.provider]:{...v[row.provider],enabled:e.target.checked}}))}/><span className="font-medium">{t('Enable connection')}</span></label>}
 {fields[row.provider].map(([key,label,max])=>{const secret=!['sender_email','model'].includes(key);return <label key={key} className="block"><span className="label">{t(label)}</span><input className="input" type={secret?'password':key==='sender_email'?'email':'text'} autoComplete="off" spellCheck={false} maxLength={max} value={draft[row.provider]?.[key]||''} required={Boolean(draft[row.provider]?.enabled&&!row.fields?.[key])} placeholder={secret&&row.fields?.[key]?t('Saved — leave blank to keep'):''} pattern={key==='model'?'gemini-[a-zA-Z0-9.-]+':undefined} onChange={e=>setDraft(v=>({...v,[row.provider]:{...v[row.provider],[key]:e.target.value}}))}/></label>;})}
 <div className="flex flex-wrap gap-2"><button className="btn-primary" type="submit"><Save size={17}/>{busy===row.provider?t('Saving…'):t('Save connection')}</button><button className="btn-secondary" type="button" disabled={!row.ready} onClick={()=>test(row.provider)}>{t('Check saved connection')}</button></div></fieldset>
 {row.provider==='gmail'&&<details className="rounded-xl bg-slate-50 p-4 text-sm leading-6"><summary className="cursor-pointer font-semibold">{t('Google setup guide')}</summary><p className="mt-3">{t('Enable Gmail API in Google Cloud. Create an OAuth client and authorize the sender with the gmail.send scope and offline access. Store the client ID, client secret, refresh token, and sender address. Staff login uses a password followed by a six-digit code; Google account sign-in is not required.')}</p><a className="mt-3 inline-block font-semibold text-red-700 underline" href="https://developers.google.com/workspace/gmail/api/auth/scopes" target="_blank" rel="noreferrer">{t('Open Google documentation')}</a></details>}
 </form>)}</div>
 <section className="panel mt-5 p-5"><h2 className="font-bold">{t('Forecasting engine')}</h2><p className={`mt-2 text-sm ${engine?.ready?'text-emerald-700':'text-amber-800'}`}>{t(engine?.message||'Check the API connection.')}</p><p className="mt-2 text-sm text-slate-600">{t('Python is detected on this server. Run the setup script if dependencies are missing. A copied virtual environment from another computer will not work.')}</p><button className="btn-secondary mt-3" disabled={Boolean(busy)} onClick={load}><RefreshCw size={17}/>{t('Check again')}</button></section></>}
 </>;
}
