import { useEffect, useState } from 'react';
import { MailCheck, Save, ShieldCheck } from 'lucide-react';
import { api } from '../lib/api.js';
import PageHeader from '../components/PageHeader.jsx';
import Toast from '../components/Toast.jsx';

export default function SettingsPage(){
 const [settings,setSettings]=useState({}),[status,setStatus]=useState(null),[busy,setBusy]=useState(false),[toast,setToast]=useState(null);
 const load=async()=>{try{const [s,st]=await Promise.all([api.get('/api/admin/settings'),api.get('/api/admin/system-status')]);const m={};for(const r of s.data||[])m[r.key]=r.value;setSettings(m);setStatus(st);}catch(e){setToast({type:'error',message:e.message});}};useEffect(()=>{load();},[]);
 async function save(){setBusy(true);try{for(const [key,value] of Object.entries(settings))await api.patch(`/api/admin/settings/${key}`,{value});setToast({message:'System settings saved.'});}catch(e){setToast({type:'error',message:e.message});}finally{setBusy(false);}}
 return <><PageHeader title="Settings" subtitle="Owner-only automation and retention settings." actions={<button className="btn-primary" onClick={save} disabled={busy}><Save size={16}/>{busy?'Saving...':'Save settings'}</button>}/>
 <div className="grid gap-5 lg:grid-cols-2"><section className="panel p-5"><h2 className="font-bold">Automation</h2><p className="mt-1 text-sm text-slate-500">The GitHub Actions scheduler calls protected job endpoints using the CRON secret.</p><div className="mt-5 space-y-4"><label className="flex items-start justify-between gap-4 rounded-xl border border-slate-200 p-4"><div><p className="text-sm font-semibold">Automatic supplier email</p><p className="mt-1 text-xs leading-5 text-slate-500">When the daily job runs, email suppliers whose assigned products need replenishment.</p></div><input type="checkbox" className="mt-1" checked={Boolean(settings.auto_supplier_email_enabled)} onChange={e=>setSettings({...settings,auto_supplier_email_enabled:e.target.checked})}/></label><label><span className="label">Email cooldown (days)</span><input type="number" min="1" max="30" className="input" value={settings.supplier_email_cooldown_days??3} onChange={e=>setSettings({...settings,supplier_email_cooldown_days:Number(e.target.value)})}/><span className="mt-1 block text-xs text-slate-500">Prevents the same recommendation set from being emailed repeatedly.</span></label><label><span className="label">Backup retention (days)</span><input type="number" min="1" max="365" className="input" value={settings.backup_retention_days??30} onChange={e=>setSettings({...settings,backup_retention_days:Number(e.target.value)})}/></label><label><span className="label">Default forecast horizon (days)</span><input type="number" min="7" max="90" className="input" value={settings.forecast_horizon_days??30} onChange={e=>setSettings({...settings,forecast_horizon_days:Number(e.target.value)})}/></label></div></section>
 <section className="space-y-5"><div className="panel p-5"><div className="flex items-start gap-3"><MailCheck className={status?.emailConfigured?'text-emerald-600':'text-amber-600'} size={22}/><div><h2 className="font-bold">Supplier email provider</h2><p className="mt-1 text-sm leading-6 text-slate-500">Brevo API status: <span className={`font-semibold ${status?.emailConfigured?'text-emerald-700':'text-amber-700'}`}>{status?.emailConfigured?'Configured':'Not configured'}</span>. Add the API key and verified sender address as server environment variables.</p></div></div></div><div className="panel p-5"><div className="flex items-start gap-3"><ShieldCheck className="text-emerald-600" size={22}/><div><h2 className="font-bold">Security defaults</h2><ul className="mt-2 space-y-2 text-sm leading-6 text-slate-600"><li>Service-role database key remains server-side only.</li><li>Staff access is role-based and public registration is not used.</li><li>Inventory changes are recorded in append-only transaction history.</li><li>Backups and ML model files use private Supabase Storage buckets.</li><li>API requests use HTTPS in deployment, Helmet headers, CORS allowlisting, validation, and rate limits.</li></ul></div></div></div></section></div><Toast toast={toast} onClose={()=>setToast(null)}/></>;
}
