import { useEffect, useState } from 'react';
import { Plus, ShieldCheck, UserRound } from 'lucide-react';
import { api } from '../lib/api.js';
import Modal from '../components/Modal.jsx';
import PageHeader from '../components/PageHeader.jsx';
import StatusBadge from '../components/StatusBadge.jsx';
import Toast from '../components/Toast.jsx';

const blank={fullName:'',email:'',password:'',role:'inventory_staff'};
export default function UsersPage(){
 const [rows,setRows]=useState([]),[modal,setModal]=useState(false),[form,setForm]=useState(blank),[busy,setBusy]=useState(false),[toast,setToast]=useState(null),[audit,setAudit]=useState([]);
 const load=async()=>{try{const [u,a]=await Promise.all([api.get('/api/admin/users'),api.get('/api/admin/audit')]);setRows(u.data||[]);setAudit(a.data||[]);}catch(e){setToast({type:'error',message:e.message});}};useEffect(()=>{load();},[]);
 async function create(){setBusy(true);try{await api.post('/api/admin/users',form);setForm(blank);setModal(false);setToast({message:'Staff account created.'});load();}catch(e){setToast({type:'error',message:e.message});}finally{setBusy(false);}}
 async function change(id,patch){try{await api.patch(`/api/admin/users/${id}`,patch);setToast({message:'User access updated.'});load();}catch(e){setToast({type:'error',message:e.message});}}
 return <><PageHeader title="Users & Security" subtitle="Owner-controlled staff accounts, roles, activation state, and audit trail." actions={<button className="btn-primary" onClick={()=>setModal(true)}><Plus size={16}/>Add staff account</button>}/>
 <div className="grid gap-5 xl:grid-cols-[1.1fr_.9fr]"><section className="panel overflow-hidden"><div className="panel-header"><div><h2 className="font-bold">Staff access</h2><p className="text-sm text-slate-500">Use the least-privilege role required for each staff member.</p></div></div><div className="divide-y divide-slate-100">{rows.map(u=><div key={u.id} className="flex flex-col gap-3 px-5 py-4 sm:flex-row sm:items-center"><div className="flex min-w-0 flex-1 items-center gap-3"><div className="rounded-full bg-slate-100 p-2.5"><UserRound size={18}/></div><div className="min-w-0"><p className="truncate text-sm font-semibold">{u.full_name||u.email}</p><p className="truncate text-xs text-slate-500">{u.email}</p></div></div><select className="input w-full sm:w-44" value={u.role} onChange={e=>change(u.id,{role:e.target.value})}><option value="inventory_staff">Inventory staff</option><option value="admin">Admin</option><option value="owner">Owner</option></select><button className={`btn ${u.active?'border border-slate-200 bg-white text-slate-700':'bg-emerald-600 text-white'} w-full sm:w-28`} onClick={()=>change(u.id,{active:!u.active})}>{u.active?'Deactivate':'Activate'}</button></div>)}</div></section>
 <section className="panel overflow-hidden"><div className="panel-header"><div className="flex items-center gap-2"><ShieldCheck size={18} className="text-emerald-600"/><h2 className="font-bold">Recent audit activity</h2></div></div><div className="max-h-[620px] divide-y divide-slate-100 overflow-y-auto">{audit.slice(0,60).map(a=><div className="px-5 py-3" key={a.id}><div className="flex items-center justify-between gap-3"><p className="text-sm font-semibold capitalize">{a.action.replaceAll('_',' ')}</p><span className="text-xs text-slate-400">{new Date(a.created_at).toLocaleString()}</span></div><p className="mt-1 text-xs text-slate-500">{a.entity_type}{a.entity_id?` · ${a.entity_id}`:''}</p></div>)}</div></section></div>
 <Modal open={modal} onClose={()=>setModal(false)} title="Create staff account" description="Accounts are created by the owner; there is no public registration." footer={<><button className="btn-secondary" onClick={()=>setModal(false)}>Cancel</button><button className="btn-primary" onClick={create} disabled={busy}>{busy?'Creating...':'Create account'}</button></>}><div className="space-y-4"><label><span className="label">Full name *</span><input className="input" value={form.fullName} onChange={e=>setForm({...form,fullName:e.target.value})}/></label><label><span className="label">Email *</span><input type="email" className="input" value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/></label><label><span className="label">Temporary password *</span><input type="password" minLength="10" className="input" value={form.password} onChange={e=>setForm({...form,password:e.target.value})}/></label><label><span className="label">Role</span><select className="input" value={form.role} onChange={e=>setForm({...form,role:e.target.value})}><option value="inventory_staff">Inventory staff</option><option value="admin">Admin</option><option value="owner">Owner</option></select></label></div></Modal><Toast toast={toast} onClose={()=>setToast(null)}/></>;
}
